export const CARD_TYPE = {
  NONE: 0,
  BBANG: 1, // 20장
  BIG_BBANG: 2, // 1장
  SHIELD: 3, // 10장
  VACCINE: 4, // 6장
  CALL_119: 5, // 2장
  DEATH_MATCH: 6, // 4장
  GUERRILLA: 7, // 1장
  ABSORB: 8, // 4장
  HALLUCINATION: 9, // 4장
  FLEA_MARKET: 10, // 3장
  MATURED_SAVINGS: 11, // 2장
  WIN_LOTTERY: 12, // 1장
  SNIPER_GUN: 13, // 1장
  HAND_GUN: 14, // 2장
  DESERT_EAGLE: 15, // 3장
  AUTO_RIFLE: 16, // 2장
  LASER_POINTER: 17, // 1장
  RADAR: 18, // 1장
  AUTO_SHIELD: 19, // 2장
  STEALTH_SUIT: 20, // 2장
  CONTAINMENT_UNIT: 21, // 3장
  SATELLITE_TARGET: 22, // 1장
  BOMB: 23, // 1장
};

export const CARD_POOL = {
  [CARD_TYPE.NONE]: 0,
  [CARD_TYPE.BBANG]: 20,
  [CARD_TYPE.BIG_BBANG]: 1,
  [CARD_TYPE.SHIELD]: 10,
  [CARD_TYPE.VACCINE]: 6,
  [CARD_TYPE.CALL_119]: 2,
  [CARD_TYPE.DEATH_MATCH]: 4,
  [CARD_TYPE.GUERRILLA]: 1,
  [CARD_TYPE.ABSORB]: 4,
  [CARD_TYPE.HALLUCINATION]: 4,
  [CARD_TYPE.FLEA_MARKET]: 3,
  [CARD_TYPE.MATURED_SAVINGS]: 2,
  [CARD_TYPE.WIN_LOTTERY]: 1,
  [CARD_TYPE.SNIPER_GUN]: 1,
  [CARD_TYPE.HAND_GUN]: 2,
  [CARD_TYPE.DESERT_EAGLE]: 3,
  [CARD_TYPE.AUTO_RIFLE]: 2,
  [CARD_TYPE.LASER_POINTER]: 1,
  [CARD_TYPE.RADAR]: 1,
  [CARD_TYPE.AUTO_SHIELD]: 2,
  [CARD_TYPE.STEALTH_SUIT]: 2,
  [CARD_TYPE.CONTAINMENT_UNIT]: 3,
  [CARD_TYPE.SATELLITE_TARGET]: 1,
  [CARD_TYPE.BOMB]: 1,
};
