/** 패킷 헤더에 대해 정의된 파일 */
export const TOTAL_HEADER_LENGTH = 12;
export const PAYLOAD_ONEOF_CASE_LENGTH = 2;
export const VERSION_LENGTH = 1;
export const SEQUENCE_LENGTH = 4;
export const PAYLOAD_LENGTH = 4;

export const PACKET_TYPE = {
  // 회원가입 및 로그인
  REGISTER_REQUEST: 1,
  REGISTER_RESPONSE: 2,
  LOGIN_REQUEST: 3,
  LOGIN_RESPONSE: 4,

  // 방 생성
  CREATE_ROOM_REQUEST: 5,
  CREATE_ROOM_RESPONSE: 6,
  // 방 목록 조회
  GET_ROOM_LIST_REQUEST: 7,
  GET_ROOM_LIST_RESPONSE: 8,
  // 방 참가
  JOIN_ROOM_REQUEST: 9,
  JOIN_ROOM_RESPONSE: 10,
  // 랜덤 방 참가
  JOIN_RANDOM_ROOM_REQUEST: 11,
  JOIN_RANDOM_ROOM_RESPONSE: 12,
  // 방 참가 알림
  JOIN_ROOM_NOTIFICATION: 13,
  // 방 나가기
  LEAVE_ROOM_REQUEST: 14,
  LEAVE_ROOM_RESPONSE: 15,
  // 방 나가기 알림
  LEAVE_ROOM_NOTIFICATION: 16,

  // 게임 시작 전, 역할 및 캐릭터 셔플 요청
  GAME_PREPARE_REQUEST: 17,
  GAME_PREPARE_RESPONSE: 18,
  GAME_PREPARE_NOTIFICATION: 19,

  // 게임 시작
  GAME_START_REQUEST: 20,
  GAME_START_RESPONSE: 21,
  GAME_START_NOTIFICATION: 22,

  // 위치 업데이트
  POSITION_UPDATE_REQUEST: 23,
  POSITION_UPDATE_NOTIFICATION: 24,

  // 카드 사용
  USE_CARD_REQUEST: 25,
  USE_CARD_RESPONSE: 26,
  // 카드 사용 알림
  USE_CARD_NOTIFICATION: 27,
  EQUIP_CARD_NOTIFICATION: 28, // 장비
  CARD_EFFECT_NOTIFICATION: 29, // 장비 효과 발동 시

  // 플리마켓
  FLEA_MARKET_NOTIFICATION: 30,
  FLEA_MARKET_PICK_REQUEST: 31,
  FLEA_MARKET_PICK_RESPONSE: 32,

  // 유저 정보 업데이트 알림(카드 사용, 체력 감소..)
  USER_UPDATE_NOTIFICATION: 33,

  // 페이즈 업데이트
  PHASE_UPDATE_NOTIFICATION: 34,

  // 리액션
  REACTION_REQUEST: 35,
  REACTION_RESPONSE: 36,

  // 턴 종료시 카드 버리기
  DESTROY_CARD_REQUEST: 37,
  DESTROY_CARD_RESPONSE: 38,

  // 게임 종료
  GAME_END_NOTIFICATION: 39,

  // 카드 선택
  CARD_SELECT_REQUEST: 40,
  CARD_SELECT_RESPONSE: 41,

  // 디버프 넘기기
  PASS_DEBUFF_REQUEST: 42,
  PASS_DEBUFF_RESPONSE: 43,
  WARNING_NOTIFICATION: 44, // 폭탄

  // 효과 알림
  ANIMATION_NOTIFICATION: 45,
};

export const ROOM_STATE_TYPE = {
  WAIT: 0,
  PREPARE: 1,
  INGAME: 2,
};

export const GLOBAL_FAIL_CODE = {
  NONE_FAILCODE: 0,
  UNKNOWN_ERROR: 1,
  INVALID_REQUEST: 2,
  AUTHENTICATION_FAILED: 3,
  CREATE_ROOM_FAILED: 4,
  JOIN_ROOM_FAILED: 5,
  LEAVE_ROOM_FAILED: 6,
  REGISTER_FAILED: 7,
  ROOM_NOT_FOUND: 8,
  CHARACTER_NOT_FOUND: 9,
  CHARACTER_STATE_ERROR: 10,
  CHARACTER_NO_CARD: 11,
  INVALID_ROOM_STATE: 12,
  NOT_ROOM_OWNER: 13,
  ALREADY_USED_BBANG: 14,
  INVALID_PHASE: 15,
  CHARACTER_CONTAINED: 16,
};

export const WARNING_TYPE = {
  NO_WARNING: 0,
  BOMB_WARNING: 1,
};

export const REACTION_TYPE = {
  NONE_REACTION: 0,
  NOT_USE_CARD: 1,
};

export const PHASE_TYPE = {
  DAY: 1,
  // EVENING: 2, 필요시 추가,
  END: 3,
};

// 인터벌 주기
// 필요한 주기가 있으면 추가해서 사용.
// 전부 초단위
export const INTERVAL = {
  SYNC_POSITION: 1,
  SYNC_GAME: 2,
  PHASE_UPDATE_DAY: 60,
  PHASE_UPDATE_END: 60,
  FLEA_MARKET_PICK: 10,
  BOMB: 5,
  BOMB_ANIMATION: 5,
  ATTACK: 10,
};

export const INTERVAL_TYPE = {
  POSITION: 0,
  PHASE_UPDATE: 1,
  GAME_UPDATE: 2,
  CHARACTER_STATE: 3,
  BOMB: 4,
  BOMB_ANIMATION: 5,
};

export const WIN_TYPE = {
  TARGET_AND_BODYGUARD_WIN: 0,
  HITMAN_WIN: 1,
  PSYCHOPATH_WIN: 2,
};

export const ANIMATION_TYPE = {
  NO_ANIMATION: 0,
  SATELLITE_TARGET_ANIMATION: 1,
  BOMB_ANIMATION: 2,
  SHIELD_ANIMATION: 3,
};

export const PROBABILITY = {
  AUTO_SHIELD: 25, // 자동 실드 확률
  SATELLITE_TARGET: 3, // 빔 확률
};
