name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: YOUR_EC2_PUBLIC_IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/bang_game
            git pull origin main
            # 필요한 서버 실행 명령 추가 (예: Docker Compose 실행)
            sudo systemctl restart your-service-name
