name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 52.79.226.3
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/bang_game
            echo "HOST=${{ secrets.HOST }}" > .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

            cho "DB_NAME=${{ secrets.DB_NAME2 }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER2 }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD2 }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST2 }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT2 }}" >> .env

            cho "DB_NAME=${{ secrets.REDIS_NAME }}" >> .env
            echo "DB_USER=${{ secrets.REDIS_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
            echo "DB_HOST=${{ secrets.REDIS_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.REDIS_PORT }}" >> .env
            git pull origin main
            npm install
            pm2 restart src/server.js || pm2 start src/server.js
